
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 23 20:14:43 CST 2012
//----------------------------------------------------

package proyecto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 42;
  public static final int MULT = 31;
  public static final int CHAR = 18;
  public static final int CASE = 41;
  public static final int RESTA = 30;
  public static final int myINTEGER_LITERAL = 48;
  public static final int INT = 20;
  public static final int STATIC = 5;
  public static final int NOT = 39;
  public static final int AND = 26;
  public static final int PUNTOyCOMA = 15;
  public static final int CLASS = 2;
  public static final int DIV = 32;
  public static final int SUMA = 29;
  public static final int myCHAR_LITERAL = 47;
  public static final int MAIN = 7;
  public static final int IF = 22;
  public static final int THIS = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int RETURN = 16;
  public static final int TRUE = 35;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int LLAVEi = 3;
  public static final int COMA = 17;
  public static final int myIDENTIFIER = 45;
  public static final int LLAVEd = 13;
  public static final int MAYOR_QUE = 28;
  public static final int BREAK = 40;
  public static final int VOID = 6;
  public static final int PARENi = 8;
  public static final int SWITCH = 43;
  public static final int PARENd = 12;
  public static final int ELSE = 23;
  public static final int PUNTO = 33;
  public static final int LENGHT = 34;
  public static final int WHILE = 24;
  public static final int CORCHETEi = 10;
  public static final int DEFAULT = 44;
  public static final int mySTRING_LITERAL = 46;
  public static final int PUBLIC = 4;
  public static final int EXTENDS = 14;
  public static final int CORCHETEd = 11;
  public static final int ASIGN = 21;
  public static final int STRING = 9;
  public static final int MENOR_QUE = 27;
  public static final int FALSE = 36;
  public static final int SYSTEM_OUT_PRINTln = 25;
}

